stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: python:slim
  script:
    - echo "Compiling the code..."
    - pip install -U twine
    - python setup.py sdist
    - echo "Compile complete."
    - twine upload dist/*
    - echo "Upload complete."
  # cache: {}
  # only:
  #       - tags