image: python:3.11-alpine

stages:
  - deploy

before_script:
   - pip install twine
   - python setup.py sdist

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $USER_NAME
    TWINE_PASSWORD: $API_KEY
    script:
      - twine upload dist/*
  only:
    - tags