Agents:
  Eberhart:
   Actions:
     - Move8
     - Noop
     - ItemAction
   Observations:
     - Combined:
         - Other
         - Walls
     - GlobalPosition
     - Battery
     - ChargePods
     - DirtPiles
     - Destinations
     - Doors
     - Items
     - Inventory
     - DropOffLocations
     - Maintainers
  Wolfgang:
    Actions:
    - Noop
    - BtryCharge
    - CleanUp
    - DestAction
    - DoorUse
    - ItemAction
    - Move8
    Observations:
    - Combined:
      - Other
      - Walls
    - GlobalPosition
    - Battery
    - ChargePods
    - DirtPiles
    - Destinations
    - Doors
    - Items
    - Inventory
    - DropOffLocations
    - Maintainers
Entities:
  Batteries: {}
  ChargePods: {}
  Destinations: {}
  DirtPiles:
    clean_amount: 1
    dirt_spawn_r_var: 0.1
    initial_amount: 2
    initial_dirt_ratio: 0.05
    max_global_amount: 20
    max_local_amount: 5
  Doors: {}
  DropOffLocations: {}
  GlobalPositions: {}
  Inventories: {}
  Items: {}
  Machines: {}
  Maintainers: {}
  Zones: {}

General:
  env_seed: 69
  individual_rewards: true
  level_name: large
  pomdp_r: 3
  verbose: false

Rules:
  BtryDoneAtDischarge: {}
  Collision:
    done_at_collisions: false
  AssignGlobalPositions: {}
  DestinationReachReward: {}
  SpawnDestinations:
    n_dests: 1
    spawn_mode: GROUPED
  DoneOnAllDirtCleaned: {}
  SpawnDirt:
    initial_n: 4
    initial_amount: 0.5
    respawn_n: 2
    respawn_amount: 0.2
    spawn_freq: 15
  EntitiesSmearDirtOnMove: {}
  DoDoorAutoClose:
    close_frequency: 10
  ItemRules:
    max_dropoff_storage_size: 0
    n_items: 5
    n_locations: 5
    spawn_frequency: 15
  MaxStepsReached:
    max_steps: 500
#  AgentSingleZonePlacement:
#    n_zones: 4
