General:
  env_seed: 69
  # Individual vs global rewards
  individual_rewards: true
  # The level.txt file to load from marl_factory_grid/levels
  level_name: eight_puzzle
  # View Radius; 0 = full observatbility
  pomdp_r: 0
  # Print all messages and events
  verbose: True
  # Run tests
  tests: false

# In the "eight puzzle" there are 8 agents standing on a 3x3 map, each with a specific destination to reach.
Agents:
  Wolfgang:
    Actions:
      Noop:
        fail_reward: -0
        valid_reward: 0
      Move4:
        fail_reward: -0.1
        valid_reward: -.01
    Observations:
      - Other
      - Walls
      - Destination
    Clones:
      - Juergen
      - Soeren
      - Walter
      - Siggi
      - Dennis
      - Karl-Heinz
      - Kevin
    # multiple agents can not stand on the same location
    is_blocking_pos: true

Entities:
  Destinations:
    # Let them spawn on closed doors and agent positions
    ignore_blocking: true
    # We need a special spawn rule...
    spawnrule:
      # ...which assigns the destinations per agent
      SpawnDestinationsPerAgent:
        # we use this parameter
        coords_or_quantity:
          # to enable and assign special positions per agent
          Wolfgang: 1
          Karl-Heinz: 1
          Kevin: 1
          Juergen: 1
          Soeren: 1
          Walter: 1
          Siggi: 1
          Dennis: 1

Rules:
  # Utilities
  WatchCollisions:
    done_at_collisions: false

  # Done Conditions
  # Done when all agents are standing on the correct destination at the same time
  DoneAtDestinationReach:
    condition: simultaneous
  DoneAtMaxStepsReached:
    max_steps: 500
