General:
  env_seed: 69
  individual_rewards: true
  level_name: narrow_corridor
  pomdp_r: 0
  verbose: true

Agents:
  Wolfgang:
    Actions:
    - Noop
    - Move8
    Observations:
    - Walls
    - Other
    - Destination
    Positions:
      - (2, 1)
      - (2, 5)
    is_blocking_pos: true
  Karl-Heinz:
    Actions:
      - Noop
      - Move8
    Observations:
      - Walls
      - Other
      - Destination
    Positions:
      - (2, 1)
      - (2, 5)
    is_blocking_pos: true

Entities:
  Destinations:
    ignore_blocking: true
    spawnrule:
      SpawnDestinationsPerAgent:
        coords_or_quantity:
          Wolfgang:
              - (2, 1)
              - (2, 5)
          Karl-Heinz:
              - (2, 1)
              - (2, 5)
    # Whether you want to provide a numeric Position observation.
    # GlobalPositions:
    #   normalized: false

Rules:
  # Utilities
  WatchCollisions:
    done_at_collisions: false
  # Done Conditions
  # DoneAtDestinationReachAny:
  DoneAtDestinationReachAll:
  DoneAtMaxStepsReached:
    max_steps: 500
