env:
  classname:          marl_factory_grid.environment.configs.marl_eval
  env_name:           "marl_eval/two_rooms_eval_config_emergent"
  n_agents:           2
  eval_render:        True
  save_and_log:       False
algorithm:
  pile-order:         "agents" # Options: "fixed", "random", "none", "agents", "dynamic", "smart" (Use "fixed", "random" and "none" for single agent training and the other for multi agent inference)
  pile-observability: "single" # Options: "single", "all"
  pile_all_done:      "distributed" # Options: "single", "all" ("single" for training, "all" and "distributed" for eval)
  auxiliary_piles:    False # Use True to see emergent phenomenon and False to prevent it


